### PR TITLE
delete unnecessary cruft

### PR DESCRIPTION
**Pull request by JacobLezberg**
Is it ok to delete the .zip with examples & the directory with all the unused assets?

### CODE REVIEW

**Comment by JacobLezberg** [comment]
Actually this should also remove the opt directory, as that is specific to your conda, rather than a real dependency of the program. I already added it to the .gitignore, but forgot to delete the folder. 

If you delete that folder before I do, feel free to remove the "Draft" status and review/merge this.

**Comment by KirbyG** [comment]
lgtm

**Comment by KirbyG** [comment]
lgtm

**Review by KirbyG — APPROVED** [review]
lgtm

**Pull request merged**
